name: quiz_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.0.2
  firebase_core: ^2.4.1
  firebase_core_platform_interface: ^4.5.3
  firebase_auth: ^4.2.8
  cloud_firestore: ^4.0.1
  firebase_storage: 11.0.10
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  google_sign_in: ^5.2.1
  email_validator: ^2.0.1
  http: ^0.13.4
  loading_animation_widget: ^1.2.0+2
  internet_connection_checker: 0.0.1
  fl_score_bar: ^0.2.4
  intl: ^0.17.0
  fl_chart: ^0.55.2
  dropdown_button2: ^1.9.2
  image_picker: ^0.8.6+1
  flutter_signin_button: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
